services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/python/app/src
      - ./.env:/home/python/app/.env
